### ISSUE TITLE
Subtitles not automatically assigned in source mode in Kodi 18

### ISSUE THREAD

**Issue by cguZZman** [cguZZman/plugin.googledrive#20]
https://forum.kodi.tv/showthread.php?tid=324784&pid=2752262#pid2752262

**Comment by vabandroid** [comment]
Let me know if you wanted to test something out. I currently have your addon installed in Kodi 18 beta 1  on Android and have lots of videos and subtitles I currently use with Source Mode.

**Comment by cguZZman** [comment]
@vabandroid I'll post a comment once is done so you can give it some testing. Thanks

**Comment by cguZZman** [comment]
Should be working now. Included in version 1.2.7 in my repository.

**Comment by avraham** [comment]
Hi,

I'm still having this problem in all my files when using source mode.

I'm using 1.2.12

This is my log file
[kodi.log](https://paste.kodi.tv/ajidunihoq)

**Comment by cguZZman** [comment]
Do you have the option enabled in the addon config? 
Can you try with the previous version 17? I don't have the source mode right now and it will help if you can do this testing first to check if it's a problem with the new kodi version.

**Comment by avraham** [comment]
I tried with version 17.6 and works as expected. 

Is there anymore information I can provide to help you find the problem in v18?

**Comment by cguZZman** [comment]
I'll reopen the issue and validate it later. Thanks for your report.
