### ISSUE TITLE
02 authorization 

### ISSUE THREAD

**Issue by thornsr57** [cguZZman/plugin.googledrive#82]
**Describe the bug**
Can't sign with code or PC code 
**To Reproduce**
4. See error or issue

**Your debug log file**
Put here the URL of your debug log file. Follow the steps in https://kodi.wiki/view/Log_file/Easy if you don't know how to get the file.

**Screenshots**

**Comment by thornsr57** [comment]
Can't login to Google drive, 02 authorization  code doesn't work or scanning the PC code

**Comment by cguZZman** [comment]
It should be working. The template to create an issue here in github is there for a reason. So please make sure you give at least the required information to be able to take a look on your issue.

**Comment by thornsr57** [comment]
Still get the 401 error code 

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 26, 2019 at 3:09 PM, Carlos Guzman<notifications@github.com> wrote:   
It should be working. The template to create an issue here in github is there for a reason. So please make sure you give at least the required information to be able to take a look on your issue.

**Comment by cguZZman** [comment]
Closing the issue until the debug log file is provided.
